### ISSUE TITLE
为什么我设置jroll.refresh()无效啊 能向下拉 但是界面显示不全高度不对

### ISSUE THREAD

**Issue by wafj999** [chjtx/JRoll#24]
我的页面是通过vue动态加载弄出来的 我在加载完毕之后调用了你的 refresh但是还是现实不全 请问怎么解决 我用的是最新版本
我打印了数据如下  其中 #main 为内容容器
 console.log($('#wrapper').height(),$('#scroller').height(),$('#main').height(),window.innerHeight)  

输出为 2025 2025 2025 1334

**Comment by wafj999** [comment]
补充一下 模拟器 可以用鼠标滚轮向下滚动 但是打包到设备上就不行了

**Comment by chjtx** [comment]
因为你的wrapper的高度没限死，设

```css
html,body{height:100%;}
#main {height:100%;}
#wrapper{height:100%;overflow:hidden;}
```

打印的数据变成（假设）：667 2025 667 667

这样`#scroller`的高度超过`#wrapper`的高度，JRoll才能计算出正确的滑动距离
